// <auto-generated />
using System;
using BancoDeEspecies.DataAccess.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BancoDeEspecies.DataAccess.Migrations
{
    [DbContext(typeof(BancoDeEspeciesDbContext))]
    [Migration("20230203234654_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Anthrome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Anthromes", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.AreaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("AreaTypes", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Biome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Biomes", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("UfId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UfId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PhylumId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhylumId");

                    b.ToTable("Classes", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContinentName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Culture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommonName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("LandscapeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Phenology")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<decimal?>("PlantedArea")
                        .HasColumnType("numeric");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int?>("SpeciesType")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeSincePlanting")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSinclePlantingUnit")
                        .HasColumnType("integer");

                    b.Property<string>("Variety")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LandscapeId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Cultures", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.CultureSpecie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GenusId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GenusId");

                    b.ToTable("CultureSpecies", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Domains", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("OrderId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Families", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Genus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("Genera", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Kingdom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DomainId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Kingdoms", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Landscape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Agroecosystem")
                        .HasColumnType("integer");

                    b.Property<int?>("AnthromeId")
                        .HasColumnType("integer");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool?>("IsProtectedArea")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Radius")
                        .HasColumnType("numeric");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<int?>("SampleAreaTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnthromeId");

                    b.HasIndex("CityId");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("SampleAreaTypeId");

                    b.ToTable("Landscapes", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.LandscapeAreaType", b =>
                {
                    b.Property<int>("AreaTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("LandscapeId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("numeric");

                    b.HasKey("AreaTypeId", "LandscapeId");

                    b.HasIndex("LandscapeId");

                    b.ToTable("LandscapeAreaTypes", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.LandscapeStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("LandscapeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Value")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("LandscapeId");

                    b.ToTable("LandscapeStatistics", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Locality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Localities", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.LocalityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("LocalityTypes", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.MaterialDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("GbifId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("MaterialDestinations", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Occurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsDuplicate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSnucOccurrence")
                        .HasColumnType("boolean");

                    b.Property<int?>("OccurenceMethodId")
                        .HasColumnType("integer");

                    b.Property<int>("OccurrenceType")
                        .HasColumnType("integer");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ThreatDegreeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OccurenceMethodId");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("ThreatDegreeId");

                    b.ToTable("Occurrences", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.OccurrenceColetaMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ColetaMethods", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.OccurrenceCulture", b =>
                {
                    b.Property<int>("CultureId")
                        .HasColumnType("integer");

                    b.Property<int>("OccurenceId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Area")
                        .HasColumnType("numeric");

                    b.Property<bool?>("IsMajority")
                        .HasColumnType("boolean");

                    b.Property<int?>("Percentage")
                        .HasColumnType("integer");

                    b.Property<string>("Phenology")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<decimal?>("Productivity")
                        .HasColumnType("numeric");

                    b.Property<string>("Stage")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("CultureId", "OccurenceId");

                    b.HasIndex("OccurenceId");

                    b.ToTable("OccurrenceCultures", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Phylum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("KingdomId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId");

                    b.ToTable("Phyla", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Reference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BibtexKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("ReferenceTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceTypeId");

                    b.ToTable("References", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.ReferenceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("text");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("ReferenceTypes", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.SampleAreaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsSnuc")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("SampleAreaTypes", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Specie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GenusId")
                        .HasColumnType("integer");

                    b.Property<int?>("IucnThreatDegree")
                        .HasColumnType("integer");

                    b.Property<int?>("KingdomId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("NationalThreatDegree")
                        .HasColumnType("integer");

                    b.Property<int?>("PhylumId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GenusId");

                    b.HasIndex("KingdomId");

                    b.HasIndex("PhylumId");

                    b.ToTable("Species", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.StudyCollectMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CollectEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CollectStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("MaterialDestinationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<int?>("SampleDrawing")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SamplingEffort")
                        .HasColumnType("numeric");

                    b.Property<string>("SamplingEffortUnit")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialDestinationId");

                    b.HasIndex("ReferenceId");

                    b.ToTable("StudyCollectMethods", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.ThreatDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("IucnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("MmaDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int?>("UfId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UfResolutionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("UfId");

                    b.ToTable("ThreatDegrees", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Uf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Ufs", (string)null);
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryCode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BiomeLandscape", b =>
                {
                    b.Property<int>("BiomesId")
                        .HasColumnType("integer");

                    b.Property<int>("LandscapesId")
                        .HasColumnType("integer");

                    b.HasKey("BiomesId", "LandscapesId");

                    b.HasIndex("LandscapesId");

                    b.ToTable("BiomeLandscape");
                });

            modelBuilder.Entity("LandscapeLocality", b =>
                {
                    b.Property<int>("LandscapesId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationsId")
                        .HasColumnType("integer");

                    b.HasKey("LandscapesId", "LocationsId");

                    b.HasIndex("LocationsId");

                    b.ToTable("LandscapeLocality");
                });

            modelBuilder.Entity("LocalityOccurrence", b =>
                {
                    b.Property<int>("LocalitiesId")
                        .HasColumnType("integer");

                    b.Property<int>("OccurencesId")
                        .HasColumnType("integer");

                    b.HasKey("LocalitiesId", "OccurencesId");

                    b.HasIndex("OccurencesId");

                    b.ToTable("LocalityOccurrence");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.City", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Uf", "Uf")
                        .WithMany("Cities")
                        .HasForeignKey("UfId");

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Class", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Phylum", "Phylum")
                        .WithMany("Classes")
                        .HasForeignKey("PhylumId");

                    b.Navigation("Phylum");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Culture", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Landscape", "Landscape")
                        .WithMany()
                        .HasForeignKey("LandscapeId");

                    b.HasOne("BancoDeEspecies.Domain.Models.CultureSpecie", "Species")
                        .WithMany("Cultures")
                        .HasForeignKey("SpeciesId");

                    b.Navigation("Landscape");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.CultureSpecie", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Genus", "Genus")
                        .WithMany("CultureSpecies")
                        .HasForeignKey("GenusId");

                    b.Navigation("Genus");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Family", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Order", "Order")
                        .WithMany("Families")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Genus", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Family", "Family")
                        .WithMany("Genera")
                        .HasForeignKey("FamilyId");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Kingdom", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Domain", "Domain")
                        .WithMany("Kingdoms")
                        .HasForeignKey("DomainId");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Landscape", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Anthrome", "Anthrome")
                        .WithMany("Landscapes")
                        .HasForeignKey("AnthromeId");

                    b.HasOne("BancoDeEspecies.Domain.Models.City", "City")
                        .WithMany("Landscapes")
                        .HasForeignKey("CityId");

                    b.HasOne("BancoDeEspecies.Domain.Models.Reference", "Reference")
                        .WithMany("Landscapes")
                        .HasForeignKey("ReferenceId");

                    b.HasOne("BancoDeEspecies.Domain.Models.SampleAreaType", "SampleAreaType")
                        .WithMany("Landscapes")
                        .HasForeignKey("SampleAreaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anthrome");

                    b.Navigation("City");

                    b.Navigation("Reference");

                    b.Navigation("SampleAreaType");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.LandscapeAreaType", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.AreaType", "AreaType")
                        .WithMany("LandscapeAreaTypes")
                        .HasForeignKey("AreaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BancoDeEspecies.Domain.Models.Landscape", "Landscape")
                        .WithMany("LandscapeAreaTypes")
                        .HasForeignKey("LandscapeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaType");

                    b.Navigation("Landscape");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.LandscapeStatistic", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Landscape", "Landscape")
                        .WithMany("LandscapeStatistics")
                        .HasForeignKey("LandscapeId");

                    b.Navigation("Landscape");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Locality", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.LocalityType", "Type")
                        .WithMany("Locations")
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Occurrence", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.OccurrenceColetaMethod", "OccurenceMethod")
                        .WithMany("Occurences")
                        .HasForeignKey("OccurenceMethodId");

                    b.HasOne("BancoDeEspecies.Domain.Models.Reference", "Reference")
                        .WithMany("Occurences")
                        .HasForeignKey("ReferenceId");

                    b.HasOne("BancoDeEspecies.Domain.Models.Specie", "Species")
                        .WithMany("Occurences")
                        .HasForeignKey("SpeciesId");

                    b.HasOne("BancoDeEspecies.Domain.Models.ThreatDegree", "ThreatDegree")
                        .WithMany("Occurences")
                        .HasForeignKey("ThreatDegreeId");

                    b.Navigation("OccurenceMethod");

                    b.Navigation("Reference");

                    b.Navigation("Species");

                    b.Navigation("ThreatDegree");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.OccurrenceCulture", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Culture", "Culture")
                        .WithMany("OccurrenceCultures")
                        .HasForeignKey("CultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoDeEspecies.Domain.Models.Occurrence", "Occurence")
                        .WithMany("OccurrenceCultures")
                        .HasForeignKey("OccurenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Culture");

                    b.Navigation("Occurence");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Order", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Class", "Class")
                        .WithMany("Orders")
                        .HasForeignKey("ClassId");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Phylum", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Kingdom", "Kingdom")
                        .WithMany("Phyla")
                        .HasForeignKey("KingdomId");

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Reference", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.ReferenceType", "ReferenceType")
                        .WithMany("References")
                        .HasForeignKey("ReferenceTypeId");

                    b.Navigation("ReferenceType");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Specie", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Genus", "Genus")
                        .WithMany("Species")
                        .HasForeignKey("GenusId");

                    b.HasOne("BancoDeEspecies.Domain.Models.Kingdom", "Kingdom")
                        .WithMany()
                        .HasForeignKey("KingdomId");

                    b.HasOne("BancoDeEspecies.Domain.Models.Phylum", "Phylum")
                        .WithMany()
                        .HasForeignKey("PhylumId");

                    b.Navigation("Genus");

                    b.Navigation("Kingdom");

                    b.Navigation("Phylum");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.StudyCollectMethod", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.MaterialDestination", "MaterialDestination")
                        .WithMany("StudyCollectMethods")
                        .HasForeignKey("MaterialDestinationId");

                    b.HasOne("BancoDeEspecies.Domain.Models.Reference", "Reference")
                        .WithMany("StudyCollectMethods")
                        .HasForeignKey("ReferenceId");

                    b.Navigation("MaterialDestination");

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.ThreatDegree", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Specie", "Species")
                        .WithMany("ThreatDegrees")
                        .HasForeignKey("SpeciesId");

                    b.HasOne("BancoDeEspecies.Domain.Models.Uf", "Uf")
                        .WithMany("ThreatDegrees")
                        .HasForeignKey("UfId");

                    b.Navigation("Species");

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Uf", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Country", "Country")
                        .WithMany("Ufs")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BiomeLandscape", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Biome", null)
                        .WithMany()
                        .HasForeignKey("BiomesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoDeEspecies.Domain.Models.Landscape", null)
                        .WithMany()
                        .HasForeignKey("LandscapesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LandscapeLocality", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Landscape", null)
                        .WithMany()
                        .HasForeignKey("LandscapesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoDeEspecies.Domain.Models.Locality", null)
                        .WithMany()
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocalityOccurrence", b =>
                {
                    b.HasOne("BancoDeEspecies.Domain.Models.Locality", null)
                        .WithMany()
                        .HasForeignKey("LocalitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoDeEspecies.Domain.Models.Occurrence", null)
                        .WithMany()
                        .HasForeignKey("OccurencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Anthrome", b =>
                {
                    b.Navigation("Landscapes");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.AreaType", b =>
                {
                    b.Navigation("LandscapeAreaTypes");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.City", b =>
                {
                    b.Navigation("Landscapes");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Class", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Country", b =>
                {
                    b.Navigation("Ufs");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Culture", b =>
                {
                    b.Navigation("OccurrenceCultures");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.CultureSpecie", b =>
                {
                    b.Navigation("Cultures");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Domain", b =>
                {
                    b.Navigation("Kingdoms");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Family", b =>
                {
                    b.Navigation("Genera");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Genus", b =>
                {
                    b.Navigation("CultureSpecies");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Kingdom", b =>
                {
                    b.Navigation("Phyla");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Landscape", b =>
                {
                    b.Navigation("LandscapeAreaTypes");

                    b.Navigation("LandscapeStatistics");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.LocalityType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.MaterialDestination", b =>
                {
                    b.Navigation("StudyCollectMethods");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Occurrence", b =>
                {
                    b.Navigation("OccurrenceCultures");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.OccurrenceColetaMethod", b =>
                {
                    b.Navigation("Occurences");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Order", b =>
                {
                    b.Navigation("Families");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Phylum", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Reference", b =>
                {
                    b.Navigation("Landscapes");

                    b.Navigation("Occurences");

                    b.Navigation("StudyCollectMethods");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.ReferenceType", b =>
                {
                    b.Navigation("References");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.SampleAreaType", b =>
                {
                    b.Navigation("Landscapes");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Specie", b =>
                {
                    b.Navigation("Occurences");

                    b.Navigation("ThreatDegrees");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.ThreatDegree", b =>
                {
                    b.Navigation("Occurences");
                });

            modelBuilder.Entity("BancoDeEspecies.Domain.Models.Uf", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("ThreatDegrees");
                });
#pragma warning restore 612, 618
        }
    }
}
